<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>ocl</string>
	</array>
	<key>name</key>
	<string>OCL</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>name</key>
			<string>comment</string>
			<key>match</key>
			<string>--[^\n]*</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.ocl</string>
			<key>match</key>
			<string>\b(import|include|library|package|endpackage|context|static|inv|post|pre)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>keyword.control.ocl</string>
			<key>match</key>
			<string>\b(if|then|else|endif|let|in|init|derive|def|body)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>support.function.ocl</string>
			<key>match</key>
			<string>\b(and|not|or|xor|implies|in|not)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>constant.language.ocl</string>
			<key>match</key>
			<string>\b(true|false|null|self)\b</string>
		</dict>
		<dict>
			<key>name</key>
			<string>support.type.ocl</string>
			<key>match</key>
			<string>\b(Bag|Boolean|Collection|Integer|OclAny|OclInvalid|OclMessage|OclVoid|OrderedSet|Real|Sequence|Set|String|Tuple|UnlimitedNatural)\b</string>
		</dict>
		<!--dict>
			<key>name</key>
			<string>identifier</string>
			<key>match</key>
			<string>\b(receive|after)\b</string>
		</dict-->
		<dict>
			<key>name</key>
			<string>entity.name.type.ocl</string>
			<key>match</key>
			<string>\b[A-Z][A-Za-z0-9_]*\b</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.ocl</string>
	<key>uuid</key>
	<string>95b1475d-639c-4eff-98f6-daf53cfd4c2b</string>
</dict>
</plist>
